services:
  backend:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - mqttbackend

  celery:
    image: celery:latest
    volumes:
      - .:/app
    depends_on:
      - backend
      - rabbitmq
      - redis
      - db
    command: celery -A mqttbackend worker --loglevel=info


  redis:
    image: redis:latest
    ports:
      - 6378:6379

  db:
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    ports:
      - 5433:5432
    restart: always
    networks:
      - mqttbackend


  rabbitmq:
    image: rabbitmq:latest
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672

  flower:
    image: mher/flower
    ports:
      - 5555:5555
    depends_on:
      - backend
      - rabbitmq
      - celery
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555

volumes:
  postgres_data:
  rabbitmq_data:


networks:
  mqttbackend:
    driver: bridge